#!/usr/bin/env sh
player="--player=spotify"
status="$(playerctl $player status)"


if [ "$status" == "Playing" ]; then
    printf "%s\n" "$(playerctl $player metadata title | cut -c -30)"
else
    echo ""
fi

